### ISSUE TITLE
Melhorar usabilidade com google forms

### ISSUE THREAD

**Issue by augustogoulart** [PyBunker/pybunker.github.io#11]
# Melhorar a usabilidade de quem hospeda
###  O processo de quem vai oferecer uma vaga não está muito amigavel

1. Fork do repositório.
2. Baixa todo o repositório localmente para editar um JSON.
3. Commita as alterações.
4. Faz um pull request.
5. Aguarda alguém aceitar a vaga.

Esse processo ainda implica em alguém abrir o código fonte do projeto e adicionar manualmente os dados da nova vaga.

## Proposta
1. Adicionar um google forms para submissão da vagas.
** Os dados de resposta são salvos em um Google sheets, que automaticamente gera uma API para a planilha.
2. Consumir a API usando [sheetrockjs](http://chriszarate.github.io/sheetrock/) e adicionar dinamicamente os dados da planilha no site.

Com isso se ganharia um sistema "dynamic-ish", mantendo a simplicidade das páginas estáticas, e facilitando a vida de quem quer oferecer uma vaga.

**Comment by gilsondev** [comment]
Como conversamos @agoulartx, agora é replicar na página inicial. Pode-se colocar a planilha como está, e depois customizando exibição com o Handlebars.

**Comment by jonatasbaldin** [comment]
Tá 🔝 

Closing!
