### ISSUE TITLE
Fazer alias no DNS para utilizar pybunker.com.br

### ISSUE THREAD

**Issue by jonatasbaldin** [PyBunker/pybunker.github.io#14]

**Comment by jamesperes-zz** [comment]
@davinirjr pode dar uma olhada por favor?

**Comment by augustogoulart** [comment]
Tentamos ontem, não rolou. Parece que o registro.br não aceita essa opção. Tentando transferir o domínio para a Godaddy.

**Comment by jamesperes-zz** [comment]
aceita sim, eu fiz no meu e é githubpages

**Comment by davinirjr** [comment]
Ué, @jamesperes, então é só mandar o passo a passo que eu faço! Mandei os prints da interface pro @agoulartx pra mostrar que não estava permitindo (manda os prints pra ele, @agoulartx).

Independente disso, vocês podem pesquisar como efetua a transferência de domínio via Registro.br ou GoDaddy que eu repasso de boa.

**Comment by augustogoulart** [comment]
Resolvido pelo @davinirjr e @jamesperes

**Comment by jonatasbaldin** [comment]
Posso ser chato e reabrir essa issue? hahahaha

Acho que deveríamos fazer com o que o domínio `pybunker.com.br` abrisse diretamente, e não um redirecionamento pro `www.pybunker.com.br`, sendo algo mais limpo na interface do usuário.

Não é nada urgente, e é bem simples de fazer. Como trocamos uma ideia no telegram, o @agoulartx disse que os passos são:

* Inverter o CNAME
* Criar um registro A para www

O que acham? @davinirjr acha que consegue fazer pra gente enquanto não transferimos o domínio?

Valeu!

**Comment by augustogoulart** [comment]
Pelo jeito o  registro.br não aceita essa opção.
![issue](https://user-images.githubusercontent.com/13952931/27614040-6cd479b8-5b75-11e7-8308-76c40789a089.jpg)

**Comment by davinirjr** [comment]
No celular não conseguia colocar imagem, então mandei para o @agoulartx.

Para CNAME não é possível deixar o nome do host em branco por essa interface, mas se souber de outro meio é só falar que providencio, @jonatasbaldin.

Já procurei saber como faz para transferir a detenção do domínio, que atualmente está sob meu CPF. 

Precisamos dos dados de quem vai receber (pessoa física ou jurídica), segundo esse post:

https://www.oficinadanet.com.br/post/8857-como-transferir-a-titularidade-de-dominio-no-registrobr

**Comment by jonatasbaldin** [comment]
Entendi. O que podemos fazer tb é usar um Route 53 da vida, já que é baratinho, aí tu aponta o registro.br pros endereços dele e nós podemos gerenciar.

O que acham? @davinirjr @agoulartx

**Comment by davinirjr** [comment]
O que for melhor pro projeto, @jonatasbaldin.

O que vocês decidirem, só me posicionem que eu procedo com as alterações necessárias.
