### ISSUE TITLE
Criar lista de eventos dentro do form

### ISSUE THREAD

**Issue by jonatasbaldin** [PyBunker/pybunker.github.io#17]
Podemos usar um dropdown do Google Forms para deixar uma lista fixa de eventos, assim fica bem padronizado. Temos que adicionar manualmente cada um quando forem surgindo (e removendo quando forem terminando).

O que acham?

**Comment by jonatasbaldin** [comment]
@jamesperes @agoulartx corrige diretamente no form, agora o input de evento é esse:
![](http://i.imgur.com/fObJdCf.png)

O que acham?

**Comment by augustogoulart** [comment]
Cara, ficou da hora! Curti demais.
